### ISSUE TITLE
[HU1] Obtención de datos

### ISSUE THREAD

**Issue by paula1999** [paula1999/Tune-in#3]
Como gestor, dado que los datos de los melómanos están almacenados, deseo obtener diariamente la información relacionada a lo que reproducen y desde dónde lo hacen.

**Comment by JJ** [comment]
Una HU siempre tiene un "dado que" o "en el contexto". Y por supuesto, tienes que precisar mucho más conceptos como "música", "escuchada" y "ubicación"
